### PR TITLE
Cards

### PR DESCRIPTION
**Pull request by rdai10**
Hey @pat270 

I noticed that the bootstrap accordion, when not placed in any container and with all its content collapsed, will shrink to be the size of its heading:

image

But if one or more cards are expanded, will take the size of the `.card-block` like the following:

image

There is no open issue for it on the [bs4 repo](https://github.com/twbs/bootstrap/issues). Is this something that we want to look into fixing? Or do you think that's acceptable behavior?

I'm also not sure how much margin there should be between each card in an accordion. The clay panel has a 5px spacing but bootstrap 4's example have them right on top of each other with no spacing. What are your thoughts on that?

### CODE REVIEW

**Comment by pat270** [comment]
@rdai, I think the reason for what you're seeing is because the accordion is inside `<div class="row">` but not inside `<div class="col-md-12">`.

**Comment by rdai** [comment]
Different rdai :) @rdai10 , Chinese too?

**Comment by rdai10** [comment]
@rdai yup :)

**Comment by pat270** [comment]
lol sorry @rdai, I expected more from Github. I'll be more careful next time.

**Pull request closed without merging**
