### PR TITLE
LPS-67852

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @dustinryerson

Hello,

I have a change for [LPS-67852](https://issues.liferay.com/browse/LPS-67852), which involves simply changing the font weight of table headers so that they appear bold, as intended. I've tested this fix in master, although I wasn't sure what to do for version information for the liferay-portal repository itself, for the fix to be used by Liferay.

Would you want me to be the one to send a pull for liferay-portal as well? If so, what should the version for the fix look like? Thanks in advance!

### CODE REVIEW

**Comment by Alec-Shay** [comment]
Also, should I make a LEXI ticket for this issue?

**Comment by pat270** [comment]
Hey @Alec-Shay, this is fine, I will send this to Liferay's Lexicon repo and it should get updated when we release the next version of Lexicon 1.0.8.

**Comment by Alec-Shay** [comment]
@pat270 Sounds good, thanks!

**Comment by Alec-Shay** [comment]
@pat270 Actually, do you know at what point Lexicon 1.0.8 is expected to be released? Just want to have some idea so that I can know whether we for sure need to give our customer an SDH for this issue, or if it's feasible to wait.

**Comment by pat270** [comment]
I can cut a new version at anytime (Nate needs to review it first tho), if it's urgent I can get Jon Mak to review it and send it to bchan.

**Comment by Alec-Shay** [comment]
Ah, alright. As long as it doesn't take weeks to proceed I think there shouldn't be a problem on our end; the client's been waiting a while but it doesn't seem urgent. Thanks again.

**Comment by pat270** [comment]
It will most likely be updated next week, just let me know if you need it sooner. On a side note, I wasn't able to use this fix because it made Lexicon table headers too bold. You can see what I changed at https://github.com/liferay/lexicon/pull/213. Thanks for the pull Alec!

**Pull request closed without merging**
